services:
  jsrl-rllib-image:
    build: .
    volumes:
    -  $PWD:/jsrl-rllib
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]